In [1]:
import torch

In [4]:
t = torch.rand(5,2)
t

tensor([[0.1835, 0.7825],
        [0.4825, 0.4151],
        [0.3132, 0.9642],
        [0.8966, 0.1929],
        [0.0420, 0.5334]])

In [5]:
t.reshape(-1,10)

tensor([[0.1835, 0.7825, 0.4825, 0.4151, 0.3132, 0.9642, 0.8966, 0.1929, 0.0420,
         0.5334]])

In [6]:
t.view(-1,10)

tensor([[0.1835, 0.7825, 0.4825, 0.4151, 0.3132, 0.9642, 0.8966, 0.1929, 0.0420,
         0.5334]])

In [7]:
t

tensor([[0.1835, 0.7825],
        [0.4825, 0.4151],
        [0.3132, 0.9642],
        [0.8966, 0.1929],
        [0.0420, 0.5334]])

In [8]:
t.view(-1,10)

tensor([[0.1835, 0.7825, 0.4825, 0.4151, 0.3132, 0.9642, 0.8966, 0.1929, 0.0420,
         0.5334]])

In [9]:
t

tensor([[0.1835, 0.7825],
        [0.4825, 0.4151],
        [0.3132, 0.9642],
        [0.8966, 0.1929],
        [0.0420, 0.5334]])

In [10]:
y = t.transpose(0,1)
y

tensor([[0.1835, 0.4825, 0.3132, 0.8966, 0.0420],
        [0.7825, 0.4151, 0.9642, 0.1929, 0.5334]])

In [12]:
t[3,1] = 42

In [13]:
y

tensor([[1.8349e-01, 4.8246e-01, 3.1317e-01, 8.9655e-01, 4.1973e-02],
        [7.8252e-01, 4.1506e-01, 9.6423e-01, 4.2000e+01, 5.3341e-01]])

In [14]:
t

tensor([[1.8349e-01, 7.8252e-01],
        [4.8246e-01, 4.1506e-01],
        [3.1317e-01, 9.6423e-01],
        [8.9655e-01, 4.2000e+01],
        [4.1973e-02, 5.3341e-01]])

In [15]:
y2 = t.contiguous().transpose(0,1)
y2

tensor([[1.8349e-01, 4.8246e-01, 3.1317e-01, 8.9655e-01, 4.1973e-02],
        [7.8252e-01, 4.1506e-01, 9.6423e-01, 4.2000e+01, 5.3341e-01]])

In [16]:
t[3,1]=0.2

In [17]:
y

tensor([[0.1835, 0.4825, 0.3132, 0.8966, 0.0420],
        [0.7825, 0.4151, 0.9642, 0.2000, 0.5334]])

In [18]:
y2

tensor([[0.1835, 0.4825, 0.3132, 0.8966, 0.0420],
        [0.7825, 0.4151, 0.9642, 0.2000, 0.5334]])

In [19]:
t

tensor([[0.1835, 0.7825],
        [0.4825, 0.4151],
        [0.3132, 0.9642],
        [0.8966, 0.2000],
        [0.0420, 0.5334]])

In [20]:
t.reshape(10,)

tensor([0.1835, 0.7825, 0.4825, 0.4151, 0.3132, 0.9642, 0.8966, 0.2000, 0.0420,
        0.5334])

In [24]:
import numpy as np
t = torch.tensor(np.arange(12)).view(4,3)
t

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])