In [1]:
import torch.nn as nn

In [2]:
import torch

In [3]:
import numpy as np

In [4]:
arr = np.random.rand(20,10,5)
arr

array([[[0.68954717, 0.32070997, 0.77382923, 0.52865265, 0.02501857],
        [0.1585266 , 0.71512548, 0.24281917, 0.36972095, 0.44917397],
        [0.16761631, 0.74080567, 0.12606262, 0.58280059, 0.84372267],
        [0.77582863, 0.38901779, 0.82313662, 0.42004803, 0.00337702],
        [0.07023763, 0.26675417, 0.78118957, 0.18743818, 0.54778668],
        [0.58125103, 0.1996878 , 0.94545049, 0.70548979, 0.34241965],
        [0.3098169 , 0.87175333, 0.20417367, 0.48737865, 0.91041149],
        [0.45324432, 0.50779213, 0.8575291 , 0.93093527, 0.60171578],
        [0.48001114, 0.35858802, 0.04723702, 0.83775076, 0.7029309 ],
        [0.96600055, 0.88637343, 0.78132504, 0.28461911, 0.64101908]],

       [[0.84027915, 0.39581387, 0.3975429 , 0.54978452, 0.44086286],
        [0.26252583, 0.93625748, 0.81845138, 0.93997423, 0.3442137 ],
        [0.88918198, 0.41936777, 0.34725302, 0.2702717 , 0.35325128],
        [0.98805312, 0.32992424, 0.28002359, 0.44161608, 0.93952023],
        [0.2163469

In [10]:
arr[:,:,2]*=10
arr[0]

array([[6.89547169e-01, 3.20709974e-01, 7.73829226e+03, 5.28652653e-01,
        2.50185683e-02],
       [1.58526599e-01, 7.15125478e-01, 2.42819165e+03, 3.69720948e-01,
        4.49173966e-01],
       [1.67616307e-01, 7.40805668e-01, 1.26062624e+03, 5.82800585e-01,
        8.43722669e-01],
       [7.75828633e-01, 3.89017792e-01, 8.23136622e+03, 4.20048031e-01,
        3.37701834e-03],
       [7.02376350e-02, 2.66754166e-01, 7.81189574e+03, 1.87438182e-01,
        5.47786678e-01],
       [5.81251033e-01, 1.99687802e-01, 9.45450490e+03, 7.05489786e-01,
        3.42419652e-01],
       [3.09816899e-01, 8.71753333e-01, 2.04173667e+03, 4.87378648e-01,
        9.10411495e-01],
       [4.53244315e-01, 5.07792132e-01, 8.57529096e+03, 9.30935270e-01,
        6.01715780e-01],
       [4.80011140e-01, 3.58588021e-01, 4.72370241e+02, 8.37750761e-01,
        7.02930896e-01],
       [9.66000551e-01, 8.86373433e-01, 7.81325043e+03, 2.84619107e-01,
        6.41019081e-01]])

## layer norm 은 다른 batch 와 관계없이 자기 안에서만 normalization 한다

In [22]:
layer = nn.LayerNorm([10,5])
layer(torch.from_numpy(arr).float()[0])

tensor([[-0.4148, -0.4149,  2.4604, -0.4148, -0.4150],
        [-0.4150, -0.4148,  0.4872, -0.4149, -0.4149],
        [-0.4150, -0.4148,  0.0534, -0.4148, -0.4147],
        [-0.4148, -0.4149,  2.6436, -0.4149, -0.4150],
        [-0.4150, -0.4149,  2.4877, -0.4150, -0.4148],
        [-0.4148, -0.4150,  3.0981, -0.4148, -0.4149],
        [-0.4149, -0.4147,  0.3436, -0.4149, -0.4147],
        [-0.4149, -0.4149,  2.7714, -0.4147, -0.4148],
        [-0.4149, -0.4149, -0.2395, -0.4147, -0.4148],
        [-0.4147, -0.4147,  2.4882, -0.4149, -0.4148]],
       grad_fn=<AddcmulBackward>)

In [23]:
layer(torch.from_numpy(arr).float())[0]

tensor([[-0.4148, -0.4149,  2.4604, -0.4148, -0.4150],
        [-0.4150, -0.4148,  0.4872, -0.4149, -0.4149],
        [-0.4150, -0.4148,  0.0534, -0.4148, -0.4147],
        [-0.4148, -0.4149,  2.6436, -0.4149, -0.4150],
        [-0.4150, -0.4149,  2.4877, -0.4150, -0.4148],
        [-0.4148, -0.4150,  3.0981, -0.4148, -0.4149],
        [-0.4149, -0.4147,  0.3436, -0.4149, -0.4147],
        [-0.4149, -0.4149,  2.7714, -0.4147, -0.4148],
        [-0.4149, -0.4149, -0.2395, -0.4147, -0.4148],
        [-0.4147, -0.4147,  2.4882, -0.4149, -0.4148]],
       grad_fn=<SelectBackward>)

In [14]:
t = torch.from_numpy(arr).float()

In [16]:
t[:,:,2]/=100

In [17]:
t[:,:,2]

tensor([[77.3829, 24.2819, 12.6063, 82.3137, 78.1190, 94.5451, 20.4174, 85.7529,
          4.7237, 78.1325],
        [39.7543, 81.8451, 34.7253, 28.0024, 18.8563, 94.6874, 49.8855, 58.5824,
         90.8748, 75.4796],
        [99.0699,  6.8022, 66.6525, 76.5857, 96.5636, 63.2689, 17.4494,  8.5534,
         38.3916, 15.6097],
        [33.4897, 30.0112,  1.5199, 29.7328, 83.4364,  2.8181, 90.6923, 10.0075,
         66.4338, 78.9314],
        [46.8487, 10.4411, 40.6435, 83.4821, 15.1662, 86.2975, 91.5671, 42.4922,
         77.2100, 24.0869],
        [39.0917, 81.7525, 23.7210,  8.1294, 46.7678, 26.3681, 36.0958, 43.2140,
         62.1904, 74.3861],
        [70.8413, 54.6495, 44.0447, 82.8031,  9.7520, 86.8293, 13.1329, 34.6005,
         56.9512, 19.8990],
        [56.9704, 69.3451, 64.0432, 96.6214, 70.6103, 34.6908, 75.2031, 44.2398,
         74.7430, 72.0511],
        [25.6572, 26.7190, 37.0885, 85.0823, 76.7094, 33.0239, 31.7204, 94.8424,
         85.2916, 83.5996],
        [41.9451,  

In [18]:
t.shape

torch.Size([20, 10, 5])

In [20]:
batch_norm = nn.BatchNorm1d(10)
batch_t = batch_norm(t)
batch_t

tensor([[[-3.8620e-01, -4.0149e-01,  2.7930e+00, -3.9287e-01, -4.1375e-01],
         [-1.8416e-01, -1.7306e-01,  2.9713e-01, -1.7995e-01, -1.7837e-01],
         [-3.0444e-01, -2.8582e-01,  9.9794e-02, -2.9095e-01, -2.8247e-01],
         [-3.7568e-02, -3.8932e-02,  2.5008e-01, -3.8823e-02, -4.0293e-02],
         [-3.2137e-01, -3.1599e-01,  1.8171e+00, -3.1816e-01, -3.0829e-01],
         [-1.5892e-01, -1.6471e-01,  1.2662e+00, -1.5704e-01, -1.6254e-01],
         [-3.3868e-01, -3.1808e-01,  3.9845e-01, -3.3217e-01, -3.1666e-01],
         [-1.2069e-01, -1.1998e-01,  9.9753e-01, -1.1443e-01, -1.1874e-01],
         [-7.0190e-02, -7.1159e-02, -3.6336e-02, -6.7336e-02, -6.8412e-02],
         [-2.7326e-01, -2.7545e-01,  1.8477e+00, -2.9199e-01, -2.8219e-01]],

        [[-3.7996e-01, -3.9838e-01,  1.2332e+00, -3.9200e-01, -3.9651e-01],
         [-1.8209e-01, -1.6865e-01,  1.4456e+00, -1.6857e-01, -1.8046e-01],
         [-2.8099e-01, -2.9626e-01,  8.1863e-01, -3.0111e-01, -2.9841e-01],
         [

In [21]:
t

tensor([[[6.8955e-01, 3.2071e-01, 7.7383e+01, 5.2865e-01, 2.5019e-02],
         [1.5853e-01, 7.1513e-01, 2.4282e+01, 3.6972e-01, 4.4917e-01],
         [1.6762e-01, 7.4081e-01, 1.2606e+01, 5.8280e-01, 8.4372e-01],
         [7.7583e-01, 3.8902e-01, 8.2314e+01, 4.2005e-01, 3.3770e-03],
         [7.0238e-02, 2.6675e-01, 7.8119e+01, 1.8744e-01, 5.4779e-01],
         [5.8125e-01, 1.9969e-01, 9.4545e+01, 7.0549e-01, 3.4242e-01],
         [3.0982e-01, 8.7175e-01, 2.0417e+01, 4.8738e-01, 9.1041e-01],
         [4.5324e-01, 5.0779e-01, 8.5753e+01, 9.3094e-01, 6.0172e-01],
         [4.8001e-01, 3.5859e-01, 4.7237e+00, 8.3775e-01, 7.0293e-01],
         [9.6600e-01, 8.8637e-01, 7.8133e+01, 2.8462e-01, 6.4102e-01]],

        [[8.4028e-01, 3.9581e-01, 3.9754e+01, 5.4978e-01, 4.4086e-01],
         [2.6253e-01, 9.3626e-01, 8.1845e+01, 9.3997e-01, 3.4421e-01],
         [8.8918e-01, 4.1937e-01, 3.4725e+01, 2.7027e-01, 3.5325e-01],
         [9.8805e-01, 3.2992e-01, 2.8002e+01, 4.4162e-01, 9.3952e-01],
    